import React, { useState } from 'react';
import { useParams, useSearchParams } from 'react-router-dom';
import { Loader2, CheckCircle, XCircle, KeyRound } from 'lucide-react';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000';

// Public reset page reached via the email link generated by
// POST /apps/:appId/users/forgot-password.
// URL shape: /app-user/reset-password/:appId?email=<e>&t=<token>
// Submits to POST /apps/:appId/users/reset-password { email, token, newPassword }.
export const AppUserResetPasswordPage: React.FC = () => {
  const { appId } = useParams<{ appId: string }>();
  const [searchParams] = useSearchParams();
  const email = searchParams.get('email') ?? '';
  const token = searchParams.get('t') ?? '';

  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [result, setResult] = useState<{ type: 'success' | 'error'; message: string } | null>(null);

  // If the link is malformed (no email or no token), don't even render the
  // form — show a friendly message instead. Hitting the redeem endpoint with
  // empty values just produces a 401; better to catch it client-side.
  const linkValid = Boolean(email && token);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!appId || submitting) return;

    if (password.length < 6) {
      setResult({ type: 'error', message: 'La contraseña debe tener al menos 6 caracteres.' });
      return;
    }
    if (password !== confirm) {
      setResult({ type: 'error', message: 'Las contraseñas no coinciden.' });
      return;
    }

    setSubmitting(true);
    setResult(null);

    try {
      const response = await fetch(
        `${API_URL}/apps/${appId}/users/reset-password`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ email, token, newPassword: password }),
        },
      );

      if (!response.ok) {
        // 401 from backend → "Token inválido o expirado." 404 → user not found.
        // Surface a unified message so we don't reveal which one.
        const body = await response.json().catch(() => ({}));
        const isExpired = response.status === 401;
        setResult({
          type: 'error',
          message: isExpired
            ? 'Este enlace ha expirado o ya fue usado. Solicita uno nuevo desde la app.'
            : body?.message ?? 'No se pudo restablecer la contraseña.',
        });
        setSubmitting(false);
        return;
      }

      setResult({
        type: 'success',
        message: 'Contraseña actualizada. Vuelve a la app e inicia sesión con tu nueva contraseña.',
      });
    } catch {
      setResult({ type: 'error', message: 'Error de red. Inténtalo de nuevo.' });
    }
    setSubmitting(false);
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4 py-12">
      <div className="w-full max-w-md bg-white rounded-2xl shadow-sm border border-gray-200 p-8">
        <div className="flex flex-col items-center text-center mb-6">
          <div className="w-12 h-12 rounded-full bg-indigo-100 flex items-center justify-center mb-3">
            <KeyRound className="text-indigo-600" size={22} />
          </div>
          <h1 className="text-xl font-bold text-gray-900">Restablecer contraseña</h1>
          {email && (
            <p className="text-sm text-gray-500 mt-1 break-all">{email}</p>
          )}
        </div>

        {!linkValid ? (
          <div className="text-center py-4">
            <XCircle className="mx-auto text-red-500 mb-3" size={36} />
            <p className="text-sm text-gray-700">
              Este enlace no es válido. Solicita uno nuevo desde la app.
            </p>
          </div>
        ) : result?.type === 'success' ? (
          <div className="text-center py-4">
            <CheckCircle className="mx-auto text-green-500 mb-3" size={36} />
            <p className="text-sm text-gray-700">{result.message}</p>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1.5">Nueva contraseña</label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                minLength={6}
                autoFocus
                className="w-full px-3 py-2.5 rounded-lg text-sm border border-gray-300 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none"
                placeholder="Mínimo 6 caracteres"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1.5">Confirmar contraseña</label>
              <input
                type="password"
                value={confirm}
                onChange={(e) => setConfirm(e.target.value)}
                required
                minLength={6}
                className="w-full px-3 py-2.5 rounded-lg text-sm border border-gray-300 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none"
                placeholder="Repite la contraseña"
              />
            </div>

            {result?.type === 'error' && (
              <p className="text-sm bg-red-50 border border-red-200 rounded-lg p-3 text-red-700">
                {result.message}
              </p>
            )}

            <button
              type="submit"
              disabled={submitting}
              className="w-full py-2.5 rounded-lg text-sm font-semibold bg-indigo-600 text-white hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {submitting ? <Loader2 className="animate-spin" size={16} /> : null}
              {submitting ? 'Actualizando...' : 'Restablecer contraseña'}
            </button>
          </form>
        )}
      </div>
    </div>
  );
};
